#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parents[1] / "src"))

from bidtabs.schemas import COMPILED_COLUMNS, STAR_SCHEMAS


def _table_md(columns):
    lines = ["| Column | Type | Nullable | Definition | Extraction Rule |", "|---|---|---|---|---|"]
    for c in columns:
        lines.append(f"| {c.name} | {c.dtype} | {c.nullable} | {c.description} | {c.source_rule} |")
    return "\n".join(lines)


def write_data_model(doc_dir: Path):
    text = """# Data Model Overview

This project is an internal bid lookup tool: it parses Bid Tabulation Excel sheets into a clean analytical extract for historical analysis. It does not report selection outcomes.

## Production Dashboard Model (Current)
The production semantic model for Power BI is generated by `scripts/build_star_schema.py` and stored in `data_out/`:
- `Projects.csv`
- `Items.csv`
- `Bids.csv`

## Relationship Pattern (Star-Like)
- `projects[project_id]` 1:* `items[project_id]`
- `items[item_id]` 1:* `bids[item_id]`
- `Bids` is the primary fact table.

## Staging/Lineage Extract
- `compiled_excel_itemized_clean.csv` remains the canonical staging extract at bidder-line grain (Project x Schedule x Line Item x Bidder), including totals rows.

## Dashboard Use (ODOT-Style Reference)
The end dashboard is designed for bid analytics similar to the ODOT example. These are the intended uses:
- Project context and slicers: `Projects`
- Item context and drilldown: `Items`
- Contractor pricing, ranking, and winner analytics: `Bids`

## ERD
```mermaid
erDiagram
  Projects ||--o{ Items : has
  Items ||--o{ Bids : has
```

## Legacy Note
- Historical schema-1/analysis-table CSVs (`dim_*`, `fact_*`) are retained under `data_out/archive_old_schema/` for reference only and are not the current production dashboard source.
"""
    (doc_dir / "data_model.md").write_text(text)


def write_compiled_dictionary(doc_dir: Path):
    intro = """# Data Dictionary: compiled_excel_itemized_clean.csv (v2)

## Totals Row Behavior
- Totals rows are identified when `item_description_raw` contains `Total Amount` or the phrase `Basis of Bid` (sheet text, case-insensitive).
- Totals rows are emitted one row per bidder with `is_totals_row=True`.
- For totals rows, `line_no`, `quantity`, `unit_code_*`, and `unit_price` are expected to be blank/null unless explicitly present.
- `schedule_total` stores the bidder-specific totals value from the totals row (bid total from sheet).

## Dashboard Use
- Filters/labels: `project_name_raw`, `letting_date`, `bid_schedule_type`, `bid_schedule_code`.
- Bidder comparisons: `bidder_name_canonical`, `bidder_type`.
- Line-item tables: `line_no`, `item_description_clean`, `quantity`, `unit_code_norm`, `unit_price`, `total_price`.
- Totals panels: `schedule_total` from totals rows (`is_totals_row=True`).

## Columns
"""
    body = _table_md(COMPILED_COLUMNS)
    (doc_dir / "data_dictionary_compiled_excel_itemized_clean_v2.md").write_text(intro + "\n" + body + "\n")


def write_analysis_dictionary(doc_dir: Path):
    lines = [
        "# Data Dictionary: Production Dashboard Schema",
        "",
        "Current production dashboard tables generated by `scripts/build_star_schema.py`.",
        "",
        "## projects.csv",
        "| Column | Type | Nullable | Definition | Source Rule |",
        "|---|---|---|---|---|",
        "| project_id | int | False | Project surrogate key. | Sequential key in build_star_schema.py |",
        "| ean | str | True | Project EAN parsed from header. | compiled project_ean |",
        "| project_name | str | True | Project title. | compiled project_name_raw |",
        "| advertise_date | str | True | Date carried from parsed letting_date (YYYY-MM-DD). | compiled letting_date -> date cast |",
        "| location | str | True | Normalized location code. | location_name_raw + config/location_dictionary.csv |",
        "| solicitation_no | str | True | Solicitation identifier. | compiled solicitation_no |",
        "| pdf_link | str | False | Source workbook filename. | compiled source_file |",
        "",
        "## items.csv",
        "| Column | Type | Nullable | Definition | Source Rule |",
        "|---|---|---|---|---|",
        "| item_id | int | False | Item surrogate key. | Sequential key in build_star_schema.py |",
        "| project_id | int | False | FK to projects. | Project join key from compiled extract |",
        "| line_no | str | True | Line number preserving leading zeros. | compiled line_no |",
        "| item_description_raw | str | False | Raw item description from sheet. | compiled item_description_raw |",
        "| specification | str | True | Parsed primary specification code. | parse_item_fields.spec_code_primary |",
        "| alternate_specification | str | True | Parsed alternate specification code(s). | parse_item_fields.spec_code_alternates |",
        "| pay_item_description | str | True | Parsed base item description. | parse_item_fields.item |",
        "| supplemental_description | str | True | Parsed qualifier text. | parse_item_fields.supplemental_description |",
        "| item | str | True | Business item key `<specification> - <pay_item_description>`. | parse_item_fields.item_display |",
        "| quantity | float | True | Estimated quantity. | compiled quantity |",
        "| unit_norm | str | True | Normalized unit code. | compiled unit_code_norm (fallback unit_code_raw) |",
        "",
        "## bids.csv",
        "| Column | Type | Nullable | Definition | Source Rule |",
        "|---|---|---|---|---|",
        "| bid_id | int | False | Bid surrogate key. | Sequential key in build_star_schema.py |",
        "| item_id | int | False | FK to items. | Item join key from parsed line identity |",
        "| contractor_name | str | False | Canonical bidder/contractor name. | compiled bidder_name_canonical |",
        "| unit_price | float | True | Unit bid price. | compiled unit_price |",
        "| total_price | float | True | Line total bid price (or unit_price x quantity fallback). | compiled total_price with fallback calc |",
        "| is_winner | bool | False | True when contractor has minimum project total for that project. | derived in build_star_schema.py |",
        "| rank | int | True | Dense rank of unit_price within item_id, excluding engineer estimate. | derived in build_star_schema.py |",
        "",
        "## Relationships",
        "- `projects[project_id]` 1:* `items[project_id]`",
        "- `items[item_id]` 1:* `bids[item_id]`",
        "",
        "## Example Join",
        "```sql",
        "SELECT p.project_name, i.item, b.contractor_name, b.unit_price, b.total_price",
        "FROM bids b",
        "JOIN items i ON i.item_id = b.item_id",
        "JOIN projects p ON p.project_id = i.project_id;",
        "```",
        "",
        "## Legacy Note",
        "- Prior schema-1 analysis tables (`dim_*`, `fact_*`) are archived under `data_out/archive_old_schema/` and are not the current production dashboard feed.",
    ]
    (doc_dir / "data_dictionary_analysis_schema.md").write_text("\n".join(lines) + "\n")


def write_extraction_rules(doc_dir: Path):
    text = """# Extraction Rules

## Header Parsing Heuristics
- Detect table header row by finding row containing `Item No.` plus at least two `Unit Price` and `Total Price` labels.
- If multiple candidates exist, choose row with strongest match for `Item Description`, `Estimated Quantity`, and `Units`.
- Parse freeform header block above table for:
  - `EAN` using regex `EAN\\s+([A-Za-z0-9-]+)`
  - `Solicitation No.` using regex `Solicitation\\s+No\\.\\s*(.+)`
  - first parseable date-like token as letting date.

## Bidder Block Detection (Merged Cells)
- On table header row, collect all `Unit Price` and `Total Price` columns.
- Pair columns in sequence.
- For each pair, scan up to 10 rows above for bidder name.
- If both columns belong to a merged range, use the merged range top-left value.
- If unmerged, accept identical values across the pair or non-blank value where the other is blank.

## Totals Row Detection
- A row is marked totals when `Item Description` contains `Total Amount` or the phrase `Basis of Bid` (sheet text, case-insensitive).
- Emit totals rows at bidder grain with `schedule_total` from bidder `Total Price` cell.

## Regexes
- Item code:
  - `\\((?:Item)\\s+([A-Za-z]-?\\d+(?:\\.\\d+)?)\\)`
  - `Item\\s+([A-Za-z]-?\\d+(?:\\.\\d+)?)`
- Section code:
  - `\\((?:Section)\\s+([0-9]{4,6})\\)`
"""
    (doc_dir / "extraction_rules.md").write_text(text)


def main():
    parser = argparse.ArgumentParser(description="Generate docs from authoritative schema definitions.")
    parser.add_argument("--docs_dir", default="./docs")
    args = parser.parse_args()

    doc_dir = Path(args.docs_dir)
    doc_dir.mkdir(parents=True, exist_ok=True)

    write_data_model(doc_dir)
    write_compiled_dictionary(doc_dir)
    write_analysis_dictionary(doc_dir)
    write_extraction_rules(doc_dir)


if __name__ == "__main__":
    main()
